<a href="https://colab.research.google.com/github/JieShenAI/kaggle/blob/main/Tutorial/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Know More:https://www.kaggle.com/kanncaa1/pytorch-tutorial-for-deep-learning-lovers/notebook

# Basics of Pytorch

In [2]:
import torch
import numpy as np

## math

In [5]:
a = torch.rand(2,2)
b = torch.rand(2,2)

In [6]:
a

tensor([[0.4307, 0.5045],
        [0.5050, 0.3694]])

In [7]:
b

tensor([[0.5078, 0.8721],
        [0.2727, 0.0625]])

In [8]:
torch.mul(a,b)

tensor([[0.2187, 0.4400],
        [0.1377, 0.0231]])

In [22]:
x_len = a.shape[0]
y_len = b.shape[1]
x_len,y_len
c = []
for i in range(x_len):
  for j in range(y_len):
    c.append(a[i][j]*b[i][j])

In [23]:
c

[tensor(0.2187), tensor(0.4400), tensor(0.1377), tensor(0.0231)]

### list转torch

[python中list、numpy、torch.tensor之间的相互转换](https://blog.csdn.net/pearl8899/article/details/110455867)

In [25]:
d = torch.Tensor(c)

In [30]:
d.view(2,-1)

tensor([[0.2187, 0.4400],
        [0.1377, 0.0231]])