<a href="https://colab.research.google.com/github/JieShenAI/kaggle/blob/main/mli/19_conv/conv2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# 输入

In [ ]:
x = torch.ones(4,6)
x[:,1] = 0
x[:,5] = 0

In [22]:
x,x.shape

(tensor([[1., 0., 1., 1., 1., 0.],
         [1., 0., 1., 1., 1., 0.],
         [1., 0., 1., 1., 1., 0.],
         [1., 0., 1., 1., 1., 0.]]), torch.Size([4, 6]))

view和reshape都是返回tensor，不是原地修改

## 输入维度分析

1. batch_size
2. input_channel

In [23]:
x = x.view(1,1,4,6)
x

tensor([[[[1., 0., 1., 1., 1., 0.],
          [1., 0., 1., 1., 1., 0.],
          [1., 0., 1., 1., 1., 0.],
          [1., 0., 1., 1., 1., 0.]]]])

In [24]:
x.shape

torch.Size([1, 1, 4, 6])

[[1,-1]]卷积核

若两列相同则返回0，两列不同返回1或者-1。

In [ ]:
K = torch.Tensor([[1,-1]])

In [10]:
conv = torch.nn.Conv2d(1,1,(1,2))

In [25]:
conv(x)

tensor([[[[-1.0967, -1.1805, -1.5718, -1.5718, -1.0967],
          [-1.0967, -1.1805, -1.5718, -1.5718, -1.0967],
          [-1.0967, -1.1805, -1.5718, -1.5718, -1.0967],
          [-1.0967, -1.1805, -1.5718, -1.5718, -1.0967]]]],
       grad_fn=<ThnnConv2DBackward0>)

# multi-kernels

K = torch.randn(16,3,5,5)

16对应的是输出的通道数

3对应的是上一次输出的通道数

5,5是卷积核

如何将设置的kernels传给conv