<a href="https://colab.research.google.com/github/JieShenAI/kaggle/blob/main/mli/conv/max_pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

In [2]:
x = torch.arange(16.).reshape(1,1,4,4)

In [3]:
x,x.shape

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]]]]), torch.Size([1, 1, 4, 4]))

# 默认参数

默认没有padding,stride默认等于kernel size

In [8]:
pool2d = nn.MaxPool2d(3)
pool2d(x)

tensor([[[[10.]]]])

# 设置padding,stride

In [10]:
pool2d = nn.MaxPool2d(2,stride=1,padding=1)
pool2d(x)

tensor([[[[ 0.,  1.,  2.,  3.,  3.],
          [ 4.,  5.,  6.,  7.,  7.],
          [ 8.,  9., 10., 11., 11.],
          [12., 13., 14., 15., 15.],
          [12., 13., 14., 15., 15.]]]])

设置任意的窗口大小

In [11]:
pool2d = nn.MaxPool2d((1,2))
pool2d(x)

tensor([[[[ 1.,  3.],
          [ 5.,  7.],
          [ 9., 11.],
          [13., 15.]]]])

# 每个通道单独计算

`torch.cat`,若想直到其他连接函数，可以查看stack

In [16]:
channel_x = torch.cat((x,x+1),1)
channel_x,channel_x.shape

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],
 
          [[ 1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.],
           [ 9., 10., 11., 12.],
           [13., 14., 15., 16.]]]]), torch.Size([1, 2, 4, 4]))

In [18]:
pool2d = nn.MaxPool2d(2)
channel_y = pool2d(channel_x)
channel_y,channel_y.shape

(tensor([[[[ 5.,  7.],
           [13., 15.]],
 
          [[ 6.,  8.],
           [14., 16.]]]]), torch.Size([1, 2, 2, 2]))