<a href="https://colab.research.google.com/github/JieShenAI/kaggle/blob/main/PyTorch_Tutorial/torch/permute.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
x = torch.arange(16.)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])

In [5]:
x = x.view(1,2,2,4)
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.]],

         [[ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [6]:
x.permute(0,2,3,1)

tensor([[[[ 0.,  8.],
          [ 1.,  9.],
          [ 2., 10.],
          [ 3., 11.]],

         [[ 4., 12.],
          [ 5., 13.],
          [ 6., 14.],
          [ 7., 15.]]]])