<a href="https://colab.research.google.com/github/JieShenAI/kaggle/blob/main/PyTorch_Tutorial/loss/CrossEntropyLoss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

参考资料：https://zhuanlan.zhihu.com/p/98785902

In [1]:
import torch
import torch.nn as nn

In [2]:
x_input=torch.randn(3,3)#随机生成输入 
print('x_input:\n',x_input) 
y_target=torch.tensor([1,2,0])#设置输出具体值 print('y_target\n',y_target)

x_input:
 tensor([[ 0.4550,  0.4055,  0.1093],
        [-0.2306,  1.2533, -0.4036],
        [-1.4791,  0.1211, -0.0784]])


In [3]:
#计算输入softmax，此时可以看到每一行加到一起结果都是1
softmax_func=nn.Softmax(dim=1)
soft_output=softmax_func(x_input)
print('soft_output:\n',soft_output)

soft_output:
 tensor([[0.3760, 0.3579, 0.2661],
        [0.1600, 0.7055, 0.1346],
        [0.0999, 0.4948, 0.4053]])


In [4]:
#在softmax的基础上取log
log_output=torch.log(soft_output)
print('log_output:\n',log_output)

log_output:
 tensor([[-0.9781, -1.0276, -1.3238],
        [-1.8328, -0.3489, -2.0058],
        [-2.3038, -0.7036, -0.9031]])


In [5]:
#对比softmax与log的结合与nn.LogSoftmaxloss(负对数似然损失)的输出结果，发现两者是一致的。
logsoftmax_func=nn.LogSoftmax(dim=1)
logsoftmax_output=logsoftmax_func(x_input)
print('logsoftmax_output:\n',logsoftmax_output)

logsoftmax_output:
 tensor([[-0.9781, -1.0276, -1.3238],
        [-1.8328, -0.3489, -2.0058],
        [-2.3038, -0.7036, -0.9031]])


In [6]:
#pytorch中关于NLLLoss的默认参数配置为：reducetion=True、size_average=True
nllloss_func=nn.NLLLoss()
nlloss_output=nllloss_func(logsoftmax_output,y_target)
print('nlloss_output:\n',nlloss_output)

nlloss_output:
 tensor(1.7791)


In [8]:
(1.0276+2.0058+2.3038)/3

1.7790666666666664

In [9]:
#直接使用pytorch中的loss_func=nn.CrossEntropyLoss()看与经过NLLLoss的计算是不是一样
crossentropyloss=nn.CrossEntropyLoss()
crossentropyloss_output=crossentropyloss(x_input,y_target)
print('crossentropyloss_output:\n',crossentropyloss_output)

crossentropyloss_output:
 tensor(1.7791)
