<a href="https://colab.research.google.com/github/JieShenAI/kaggle/blob/main/PyTorch_Tutorial/mLi/linear_regresson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

原文链接：https://zh-v2.d2l.ai/chapter_linear-networks/linear-regression-concise.html#id2

In [3]:
import numpy as np
import torch
from torch.utils import data
normal = torch.normal
rand = torch.rand
randn = torch.randn
matmul = torch.matmul
reshape = lambda x, *args, **kwargs: x.reshape(*args, **kwargs)

In [4]:
def synthetic_data(w, b, num_examples):
    """生成y=Xw+b+噪声
    Defined in :numref:`sec_linear_scratch`"""
    X = normal(0, 1, (num_examples, len(w)))
    y = matmul(X, w) + b
    y += normal(0, 0.01, y.shape)
    return X, reshape(y, (-1, 1))


真实的w和b

In [5]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)

In [ ]:
print(type(features))
print(type(labels))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [ ]:
labels

In [6]:
def load_array(data_arrays, batch_size, is_train=True):
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [7]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [8]:
# nn是神经网络的缩写
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [9]:
net[0].weight.data

tensor([[-0.5667, -0.6813]])

In [11]:
net[0].weight.data.normal_(0,0.01)

tensor([[0.0181, 0.0087]])

In [12]:
net[0].bias.data

tensor([0.6919])

In [13]:
net[0].bias.data.fill_(0)

tensor([0.])

In [14]:
loss = nn.MSELoss()

In [15]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [16]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000229
epoch 2, loss 0.000103
epoch 3, loss 0.000103


In [17]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

w的估计误差： tensor([-0.0004, -0.0001])
b的估计误差： tensor([0.0007])
